# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 14:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoRest', '0002_auto_20170830_1655'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ToDoElemnts',
            new_name='ToDoElements',
        ),
    ]
